markdown: kramdown
permalink: /:title.html
url: https://roguesir.github.io
lsi: true
rouge: true
safe: true

# presonal config
title: roguesir's Blog
feed: /atom.xml
comments: disqus

author:
  name: roguesir
  nickname: roguesir
  email: li_xu0214@163.com
  gmail: li_xu0214@163.com
  qqmail: li_xu0214@163.com
  qqlist: li_xu0214@163.com
  site: http://www.roguesir.top

seo:
  keyword:
  description:
